apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret }}
  jwt-refresh-secret: {{ .Values.secrets.jwtRefreshSecret }}
